---
- name: GitHub Pull Request  
  hosts: all
  vars:
  - destdir: ~/Desktop/CS504-Project-HessnerNicole/Submission1/CS504-IP01-AnsibleTest
  - repo: https://github.com/CityUhessnern/CS504-IP01-AnsibleTest
  vars_prompt:
  
  - name: "commitBranch"
    prompt: Please enter the name of the local branch you would like to update.
    private: no

  - name: "commitMessage"
    prompt: Please input message to include with commit.
    private: no

  - name: "remoteBranch"
    prompt: Please input the name of the remote branch you would like to get updates from.
    private: no

  tasks:

    - name: switchbranch
      shell: 
        git checkout -b '{{commitBranch}}'
      args:
        chdir: '{{destdir}}'
      ignore_errors: yes
      tags:
        -always
    
    - name: Git - Adding
      shell:
        git add --all
      args:
        chdir: "{{destdir}}"
      ignore_errors: yes

    - name: Git - Commiting
      shell: 
        git commit -m '{{commitMessage}}'
      args:
        chdir: "{{destdir}}"
      ignore_errors: yes

    - name: Git - Pull
      shell: git pull origin '{{remoteBranch}}'
      args:
        chdir: "{{destdir}}"
      ignore_errors: yes
...
