---
- name: GitHub Pull Request  
  hosts: localhost
  vars:
  - destdir: ~/Desktop/CS504-Project-HessnerNicole/Submission1/CS504-IP01-AnsibleTest
  vars_prompt:
  - name: "prTitle"
    prompt: Please provide a title for the pull request.
    private: no
  
  - name: "commitBranch"
    prompt: Please enter the name of the branch you would like to use.
    private: no

  - name: "commitMessage"
    prompt: Please input message to include with commit.
    private: no

  - name: "prBody"
    prompt: Please provide more information about your pull requestion in the body.
    private: no

  tasks:

    - name: switchbranch
      shell: 
        git checkout -b '{{commitBranch}}'
      args:
        chdir: '{{destdir}}'
      ignore_errors: yes
      tags:
        -always
    
    - name: Git - Adding
      shell:
        git add --all
      args:
        chdir: "{{destdir}}"
      ignore_errors: yes

    - name: Git - Commiting
      shell: 
        git commit -m '{{commitMessage}}'
      args:
        chdir: "{{destdir}}"
      ignore_errors: yes
    - name: Git - Push
      shell: git push --set-upstream origin '{{commitBranch}}'
      args:
        chdir: "{{destdir}}"
      ignore_errors: yes

    - name: createPullRequest
      shell:
        gh pr create -a @me --title '{{prTitle}}' --body '{{prBody}}'
      args:
        chdir: '{{destdir}}'
...
