---
- name: Git Reset
  hosts: all
  vars:
  - destdir: ~/Desktop/CS504-Project-HessnerNicole/Submission1/AnsibleForkTest
  vars_prompt:
  - name: "branch"
    prompt: Please provid the remote branch name.
    private: no

  tasks:
   
  - name: Git - Log
    shell: 
      git log --oneline
    register: gitlog
  - debug:
      var: gitlog.stdout 

  - name: GitReset
    vars_prompt:
      - name: "checksum"
        prompt: Please provide the checksum of the commit you would like to roll back to.
        private: no
    shell:
      gh reset --hard "{{checksum}}"
  
  - name: forcePush
    shell:
      git push origin "+{{branch}}"
    register: forcePush
  - debug:
      var: forcePush.stdout

...
